# Generated by Django 3.2.22 on 2023-10-30 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demoapp', '0002_auto_20231030_1132'),
    ]

    operations = [
        migrations.CreateModel(
            name='work',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='', verbose_name='pics')),
                ('name', models.CharField(max_length=250)),
                ('details', models.TextField()),
            ],
        ),
    ]
